### PR TITLE
Handle Runner failure and Sequence errors on Sequence start

### PR DESCRIPTION
**Pull request by pietrzakacper**
This addresses both: https://app.clickup.com/t/24308805/SCP-3756 and https://app.clickup.com/t/24308805/SCP-3757

Now starting a sequence through API or CLI should properly exit with error in the following cases:
1. Runner process exited with non zero code before receiving PANG message
2. Sequence entrypoint file throws when importing it (e.g. syntax errors)
3. Sequence is an empty array 

### 1. Crashing runner process
1. Add somewhere in global scope of `packages/runner/src/runner.ts`
```ts
throw new Error("OOOPS");
``` 
2. Run STH: 
```bash
yarn start:dev
```
3. In a new terminal run CLI:
```
npx ts-node packages/cli/src/bin/index.ts seq send ./packages/reference-apps/hello-alice-out.tar.gz
npx ts-node packages/cli/src/bin/index.ts seq start -
```
4. You should get similar output:
image

### 2. Sequence entrypoint file is invalid
1. Add somewhere in global scope of some ref-app and then build it
```ts
throw new Error("OOOPS");
``` 
2. Run STH: 
```bash
yarn start:dev
```
3. In a new terminal run CLI:
```bash
npx ts-node packages/reference-apps/<path-to-your-sequence>
npx ts-node packages/cli/src/bin/index.ts seq start -
```
4. You should get similar output:
image

### 3. Empty sequence
Do the same as in 2nd test, just export an empty array:
```ts
const app: any[] = []
export default app;
```

### CODE REVIEW

**Comment by alicja-gruzdz** [comment]
@jan-warchol when you have a free moment please take a look at it, it solves two of the issues you have reported.

**Comment by jan-warchol** [comment]
> @jan-warchol when you have a free moment please take a look at it, it solves two of the issues you have reported.

Thanks, I almost missed it! I'll check how it works with python runner.

**Comment by jan-warchol** [comment]
Ok, so the first case (crashing runner) works nice :+1: , but in the second case there is no difference in case of python runner (meaning that I get a `200 OK` while the sequence crashes). I suppose this is because python runner loads the sequence after sending the PANG.

(To reproduce, just add `raise SyntaxError` to some python sequence, send it and try starting.)

I guess the question is: does it indicate a problem with python runner, or should we change the detection method?

**Comment by alicja-gruzdz** [comment]
> I guess the question is: does it indicate a problem with python runner, or should we change the detection method?

Thanks for checking it. Indeed, you're right. It looks like we Node and Python Runner behave differently in this regard. From what I see in Python Runner the PANG is sent before detecting the Sequence in https://github.com/scramjetorg/transform-hub/blob/4b9aa51bd08ca552e2fab53d3d478f83be1ecb75/packages/python-runner/runner.py#L175. 
In Node the PANG goes out of the Runner only if it passes the detection in 
https://github.com/scramjetorg/transform-hub/blob/devel/packages/runner/src/runner.ts#L407

Please correct me if I'm wrong.
If so, it would be better to modify it in the Python Runner to behave like in the Node Runner.

From what @MichalCz mentioned this week if the PANG goes out of the Runner it means the required Sequence's structure is valid and we do not need to raise an API error on Sequence start.

**Comment by alicja-gruzdz** [comment]
Thanks Kacper for taking this herd of fixes.

Verify:
1. As long as the error is thrown before PANG the API error is returned :heavy_check_mark: 
before_getSequence

2. Incorrect Sequence main file :heavy_check_mark: 
Sequence_entrypoint_err

3. Empty Sequence :heavy_check_mark: 
empty

**Review by alicja-gruzdz — APPROVED** [review]

**Comment by pietrzakacper** [comment]
@jan-warchol I'm merging as this PR already brings some value. I see two options:
1. We load the sequence before the pang in python-runner
2. We have a special kind of monitoring message that is specifically sent after the sequence is loaded and verified (e.g. checked for correct export structure). The runner should send that message or quit.

Either way we have to modify the python runner in order to check to do any error handling in send sequence endpoint.

**Comment by MichalCz** [comment]
Yes, in my view PANG means that we've got everything working and the syntax is ok.

**Pull request merged**
