### PR TITLE
Feat/CLI Topic Create Delete

### PR DESCRIPTION
**Pull request by ErykSol**
This PR:
-adds new endpoint POST /topics and DELETE /topics/:topic to add and remove topics
-provides SI commands `topic create ` and `topic delete`.
- changes topic to Duplex class
- do some code cleaning around service discovery

To test run from root:
- yarn run start:dev:cli topic create testTopicName
- yarn run start:dev:cli topic delete testTopicName

Previous class diagram:
host_diagramPrev

Currnet class diagram:
host_diagram

Docs to add after merge in:
https://github.com/scramjetorg/scramjet-cpm-dev/pull/532

**Review checks:**

- [x] Verify and confirm operation (please post a screenshot) 
- [x] All STH tests pass
- [ ] All [Scramjet Cloud Platform](https://docs.scramjet.org/platform) tests pass
- [x] Documentation is updated or no changes

### CODE REVIEW

**Comment by a-tylenda** [comment]
Error handling for code 415. Can we inform the user about using the right content type? A new topic is being created with a `contentType: 'application/x-ndjson'`. 

```bash
yarn run start:dev:cli topic create testTopicName
yarn run v1.22.19
$ ts-node packages/cli/src/bin/index.ts topic create testTopicName
{
  id: 'testTopicName',
  origin: { id: '::', type: 'hub' },
  state: 'flowing',
  contentType: 'application/x-ndjson'
}
Done in 2.67s.
```

when I want to send some data to this topic I get and error:
```
$ yarn run start:dev:cli topic send testTopicName

Error: Failed to request 'http://127.0.0.1:8000/api/v1/topic/testTopicName' with code 415.
error Command failed with exit code 1.
```
when I add the content-type option, it works just fine (in `si topic send` and `si topic get` default content-type is `"text/plain"`):
```
$ yarn run start:dev:cli topic send testTopicName -t application/x-ndjson
yarn run v1.22.19
$ ts-node packages/cli/src/bin/index.ts topic send testTopicName -t application/x-ndjson
sdf
sdf
sdf
sf
```
Can we add some info for the users to apply the correct content-type? (Error code 415)

**Comment by a-tylenda** [comment]
What about deleting topics, which are in use? I mean topics that have hanging/opened requests like GET/POST?

Check out the screenshot:
image

- I `send topic` in one terminal
- I `get topic` in another terminal
- I delete topic
- I keep sending data, but do not get any

Should `topic delete` close POST/GET requests if there are any open?

**Comment by ErykSol** [comment]
> What about deleting topics, which are in use? I mean topics that have hanging/opened requests like GET/POST?
> 
> Check out the screenshot: image
> 
> * I `send topic` in one terminal
> * I `get topic` in another terminal
> * I delete topic
> * I keep sending data, but do not get any
> 
> Should `topic delete` close POST/GET requests if there are any open?

Impossible to manage that, without map of consumers and providers, which is not in plans anywhere near, so this is the minimum possible implementation for now :/

**Review by alicja-gruzdz — APPROVED** [review]

**Comment by a-tylenda** [comment]
verified after rebase:

creating topic:

```bash
$ yarn start:dev:cli topic create newTopic
yarn run v1.22.19
$ ts-node packages/cli/src/bin/index.ts topic create newTopic
{
  id: 'newTopic',
  origin: { id: '::', type: 'hub' },
  state: 'flowing',
  contentType: 'text/plain'
}
Done in 2.70s.

✔ ~/shared/transform-hub [feat/topic_create_delete|✚ 1…1⚑ 1] 
$ yarn start:dev:cli topic ls
yarn run v1.22.19
$ ts-node packages/cli/src/bin/index.ts topic ls
[
  {
    contentType: 'text/plain',
    localProvider: '',
    topic: 'newTopic',
    topicName: 'newTopic'
  }
]
Done in 2.70s.
```

Check data flow:

image

Delete topic:

```bash
$ yarn start:dev:cli topic delete newTopic
yarn run v1.22.19
$ ts-node packages/cli/src/bin/index.ts topic delete newTopic
{ message: 'Topic newTopic removed' }
Done in 2.69s.
```

**Review by a-tylenda — APPROVED** [review]

**Pull request merged**
