### PR TITLE
Add space client to AppContext

### PR DESCRIPTION
**Pull request by patuwwy**
**What?**  
```
this.space: ManagerClient
```

**Usage:**
- Get information about Hubs connected to Space.
- List entities on all Hosts connected to Space.
- Send Sequences, Start Instances on the other Hubs connected to Space.
- Disconnect Hubs from Space.
- And more, please refer to [ManagerClient](https://github.com/scramjetorg/transform-hub/blob/devel/packages/manager-api-client/src/manager-client.ts)

Sample Sequence printing Space version and the list of connected Hubs to stdout:
```
// sequence.ts
/* eslint-disable no-console */
import { InertApp } from "@scramjet/types";
import { Readable } from "stream";

module.exports = async function(_stream: Readable) {
    const spaceClient = this.space;

    const version = await spaceClient.getVersion();
    const hosts = await spaceClient.getHosts();

    console.log("Instance output start");
    console.log("Manager", spaceClient);
    console.log("Manager version", version);
    console.log("Hubs connected to space", hosts);
    console.log("Instance output end");
} as InertApp;
```

**Review checks:**

These aspects need to be checked by the reviewer:

- [ ] Verify and confirm operation (please post a screenshot) 
- [x] All STH tests pass
- [ ] All [Scramjet Cloud Platform](https://docs.scramjet.org/platform) tests pass
- [ ] Documentation is updated or no changes

when host is not connected all ManagerClient requests return 404

### CODE REVIEW

**Review by alicja-gruzdz — APPROVED** [review]
a really clever idea, thanks for your help with this.

**Comment by patuwwy** [comment]
image

**Review by a-tylenda — APPROVED** [review]
Verified on the stage environment:
image

**Comment by a-tylenda** [comment]
verified after rebase:
```bash
✔ ~/shared/transform-hub/bdd/data/sequences/seq [feature/space-client|…1⚑ 1] 
11:21 $ si inst stdout -
Instance output start
Manager ManagerClient { apiBase: 'http://scramjet-host/api/v1/cpm/api/v1' }
Manager version {
  service: '@scramjet/manager',
  apiVersion: 'v1',
  version: '0.32.4',
  build: '30f6943'
}
Hubs connected to space [
  {
    id: 'sth-0',
    info: {
      created: '2023-06-30T11:29:22.850Z',
      lastConnected: '2023-06-30T11:29:23.141Z'
    },
    healthy: true,
    isConnectionActive: true,
    selfHosted: false,
    description: '',
    tags: []
  },
  {
    id: 'SELF_HOSTED_STH-1',
    info: {
      created: '2023-07-04T09:08:02.331Z',
      lastConnected: '2023-07-04T09:08:04.449Z',
      lastDisconnected: '2023-07-04T09:09:33.469Z'
    },
    healthy: false,
    isConnectionActive: false,
    selfHosted: true,
    description: 'Some description',
    tags: [ 'tag1', ' tag2' ]
  },
  {
    id: 'SHH-1',
    info: {
      created: '2023-07-03T09:11:39.747Z',
      lastConnected: '2023-07-03T09:11:41.080Z',
      lastDisconnected: '2023-07-03T09:18:32.273Z'
    },
    healthy: false,
    isConnectionActive: false,
    selfHosted: true,
    description: 'My awesome Self-Hosted Hub <3',
    tags: [ 'scramjet', ' samples' ]
  },
  {
    id: 'shh-1',
    info: {
      created: '2023-07-07T11:21:14.523Z',
      lastConnected: '2023-07-07T11:21:14.798Z'
    },
    healthy: true,
    isConnectionActive: true,
    selfHosted: true,
    description: 'My awesome Self-Hosted Hub <3',
    tags: [ 'scramjet', ' samples' ]
  }
]
Instance output end
```

and logs from sth:
```bash
2023-07-07T11:21:24.801Z TRACE CSIController [b118d163] Instance started 
2023-07-07T11:21:24.801Z TRACE Host [shh-1] CSIController started [ 'b118d163-db38-474a-908f-ff7c4777f019' ]
2023-07-07T11:21:24.801Z TRACE CPMConnector [shh-1] Send instance status update [ 0 ]
2023-07-07T11:21:24.801Z TRACE CPMConnector [shh-1] Instance status update sent [ 0 ]
2023-07-07T11:21:24.802Z DEBUG Host [shh-1] Instance limits [ { memory: 512 } ]
2023-07-07T11:21:24.802Z DEBUG LokiAdapter [shh-1] Pushing log entry [ '["Instance started",{"version":"0.34.4","environment":"atylenda-scramjet-vm","hostSize":"m","ip":"51.254.13.238","adapter":"process","id":"b118d163-db38-474a-908f-ff7c4777f019","language":"js","seqId":"e1d46f5b-b7c0-4007-b0f1-ec572722e361"}]' ]
2023-07-07T11:21:24.804Z DEBUG Host [shh-1] Request [ 'date: 2023-07-07T11:21:22.278Z, method: POST, url: /api/v1/sequence/e1d46f5b-b7c0-4007-b0f1-ec572722e361/start, status: 200' ]
2023-07-07T11:21:24.811Z INFO  Host [shh-1] SPACE REQUEST [ '/api/v1/cpm/api/v1/version', 'version' ]
2023-07-07T11:21:24.811Z INFO  CPMConnector [shh-1] make HTTP Req to CPM [ 'https://api-hybrid.scp.ovh/api/v1/cpm/org-f8d19d60-0dc6-446b-9794-c701f5c3a584-manager/api/v1/version' ]
2023-07-07T11:21:24.812Z INFO  VerserClient Creating muxed channel in verser connection 
2023-07-07T11:21:24.887Z DEBUG Host [shh-1] Request [ 'date: 2023-07-07T11:21:24.812Z, method: GET, url: /api/v1/cpm/api/v1/version, status: 200' ]
2023-07-07T11:21:24.893Z INFO  Host [shh-1] SPACE REQUEST [ '/api/v1/cpm/api/v1/list', 'list' ]
2023-07-07T11:21:24.893Z INFO  CPMConnector [shh-1] make HTTP Req to CPM [ 'https://api-hybrid.scp.ovh/api/v1/cpm/org-f8d19d60-0dc6-446b-9794-c701f5c3a584-manager/api/v1/list' ]
2023-07-07T11:21:24.893Z INFO  VerserClient Creating muxed channel in verser connection 
2023-07-07T11:21:24.926Z DEBUG Host [shh-1] Request [ 'date: 2023-07-07T11:21:24.893Z, method: GET, url: /api/v1/cpm/api/v1/list, status: 200' ]
2023-07-07T11:21:24.929Z TRACE Host [shh-1] PANG received [ { provides: '', requires: undefined, contentType: '' } ]
2023-07-07T11:21:24.929Z TRACE CSIController [b118d163] Got message: SEQUENCE_COMPLETED. 
```

**Pull request merged**
