### PR TITLE
Feat/get sequence

### PR DESCRIPTION
**Pull request by piotrek6641**
What: 
Finding list of ID's for a sequences with a given name.
Clickup:
https://app.clickup.com/t/24308805/VDM-1298

**How to test:**
- si seq deploy packages/forever.tar.gz
- ts-node packages/cli/src/bin/index.ts sequence list -n @scramjet/js-forever

**Review checks:**

These aspects need to be checked by the reviewer:

- [ ] Verify and confirm operation (please post a screenshot) 
- [ ] All STH tests pass
- [ ] All [Scramjet Cloud Platform](https://docs.scramjet.org/platform) tests pass
- [ ] Documentation is updated or no changes

### CODE REVIEW

**Comment by piotrek6641** [comment]
Needs validation of name when new sequence is being uploaded/ and functionality moved to a different file

**Comment by piotrek6641** [comment]
This PR doesn't include method to prevent user from sending multiple sequences with the same name as stated in https://github.com/scramjetorg/transform-hub/issues/889 . After discussion with @alicja-gruzdz we currently don't plan to implement this functionality

**Review by ErykSol — CHANGES_REQUESTED** [review]

**Review by ErykSol — APPROVED** [review]

**Comment by alicja-gruzdz** [comment]
Then successful it looks great:
Screenshot from 2023-07-28 17-01-51

**Comment by alicja-gruzdz** [comment]
Then it does not find the Sequence it throws an error which we need to handle:
Screenshot from 2023-07-28 17-03-55

**Comment by alicja-gruzdz** [comment]
> Then it does not find the Sequence it throws an error which we need to handle: Screenshot from 2023-07-28 17-03-55

@piotrek6641 checked it is due to running it with ts-node

**Review by alicja-gruzdz — APPROVED** [review]

**Pull request merged**
