### PR TITLE
Show sequence upload progress in CLI with --progress flag

### PR DESCRIPTION
**Pull request by patuwwy**
edited.

**What?**  
```
$ si seq <send|deploy> big-sequence.tar.gz --progress
Uploading... █████░░░░░░░░░░░░░░░░░░░ 21%, 512/2395KB
```
and summary
```
Sequence package uploaded (size 2395KB)
```

**Why?**  
https://github.com/scramjetorg/transform-hub/issues/707

**Usage:**
```
si seq send big-sequence.tar.gz --progress
```

**How it works:**
it breaks piping stdout to targets as it is writing progress to stdout.

**Review checks:**

These aspects need to be checked by the reviewer:

- [ ] Verify and confirm operation (please post a screenshot) 
- [x] All STH tests pass
- [ ] All [Scramjet Cloud Platform](https://docs.scramjet.org/platform) tests pass
- [ ] Documentation is updated or no changes

### CODE REVIEW

**Comment by daro1337** [comment]
LGTM

```bash
~/repo/transform-hub (feature/cli-seq-send-progress)$ dist/cli/bin/index.js seq send ~/repo/reference-apps/js/healthy-sequence.tar.gz --progress
Sequence package uploaded (size 39556KB)             
Request ok: https://api.beta.scramjet.cloud/api/v1/space/org-<redacted>/api/v1/sth/sth-0/api/v1/sequence status: 200 OK
```

**Comment by alicja-gruzdz** [comment]
Awesome! 
Wow, that was crazy rapid dev

**Comment by BKscramjet** [comment]
Task linked: [SHN-951 Show sequence upload progress in CLI with --progress flag](https://app.clickup.com/t/24308805/SHN-951)

**Comment by alicja-gruzdz** [comment]
Thanks, Patryk! That is incredibly useful for uploading Machine Learning apps.
I'm now sipping tea and admiring how the whole big ass TensorFlow lib uploads to Beta :raised_hands: 
 
Screenshot from 2022-09-29 22-25-08

**Review by alicja-gruzdz — APPROVED** [review]

**Comment by patuwwy** [comment]
> Thanks, Patryk! That is incredibly useful for uploading Machine Learning apps. I'm now sipping tea and admiring how the whole big ass TensorFlow lib uploads to Beta 🙌
> 
> Screenshot from 2022-09-29 22-25-08

Thx for the screenshot. Bug found.

**Comment by alicja-gruzdz** [comment]
> Thx for the screenshot. Bug found.

Thanks for spotting, Patryk.
Now the progress bar looks much better on my ubuntu :star_struck: Nicely done!


Screenshot from 2022-10-03 12-25-23

**Comment by patuwwy** [comment]
@alicja-gruzdz could you fix it pls? can't reproduce negative size

**Comment by alicja-gruzdz** [comment]
> @alicja-gruzdz could you fix it pls? can't reproduce negative size

sure, I took a look and the issue is with the signed right shift (when covering bytes -> kb)
Maybe we could use the unsigned right shift?

```
bytes = 2205447557  
console.log(bytes >> 10); // -2040547

kb = Math.round(bytes/1024)
console.log(kb); // 2153757

console.log(bytes >>> 10); // 2153757
```

**Pull request merged**
