### PR TITLE
Fix not passing error from prerunner

### PR DESCRIPTION
**Pull request by patuwwy**
fix for #295 

before: docker sequence adapter did not handle the error from PreRunner and tried to parse the data from package.json
```
2022-02-26T14:34:56.686Z ERROR DockerSequenceAdapter <SequencePackageJSON> decoder failed at key "main" with error: undefined is not a valid string [ '9a0798a7-92f9-4708-870b-fe44cab30e72' ]
```

with this fix
```
2022-02-26T15:03:48.948Z DEBUG DockerSequenceAdapter PreRunner response [ { error: 'Invalid pkg tar.gz archive' } ]
2022-02-26T15:03:48.948Z ERROR DockerSequenceAdapter PreRunner failed [ 'Invalid pkg tar.gz archive' ]
```

response for `POST /sequence`:
```
HTTP/1.1 422 Unprocessable Entity
...

{"error":{"code":"PRERUNNER_ERROR","data":"Invalid pkg tar.gz archive"}}
```

### CODE REVIEW

**Comment by alicja-gruzdz** [comment]
Zrzut ekranu z 2022-03-02 12-32-37

**Review by alicja-gruzdz — APPROVED** [review]
In Docker Adapter it works great.
I assume that this PR does not include Process Adapter that needs to be handled separately (currently no meaningful info about the cause of error there - I only checked while I was at it). I'm also not sure about k8s.

**Comment by alicja-gruzdz** [comment]
> This is a huge error log in the right panel. let me try to make it a bit shorter.

Indeed, I didn't want to bother you with it. If you can do something about it, it will be excellent.

**Comment by patuwwy** [comment]
image

**Comment by patuwwy** [comment]
> I assume that this PR does not include Process Adapter that needs to be handled separately (currently no meaningful info about the cause of error there - I only checked while I was at it). I'm also not sure about k8s.

added to Process Adapter as well
no k8s yet

**Comment by alicja-gruzdz** [comment]
> added to Process Adapter as well

It's working great, thanks.
Zrzut ekranu z 2022-03-03 09-17-17

**Pull request merged**
