### PR TITLE
[SCP-3733] Hide only the not implemented features

### PR DESCRIPTION
**Pull request by a-tylenda**
### Env `NODE_ENV=development` now refers only to commands which await implementation:
- `si hub create`
- `si scope add`
- `si scope save`
- `si space create`
- `si space delete`
- `si space update`
- `si topic create`
- `si topic delete`

### Commands revealed for the beta users (`config { env: 'production' }`):
- `si scope`
- `si space`

**hub**
- `si hub use`

**sequence**
- `si seq start --output-topic <string>` 
- `si seq start --input-topic <string>` 

### CLI descriptions (--help):
- typos corrected
- improved styling and spelling to make it uniform and more user-friendly
- added links to CLI docs and scramjet.org

This is how it looks after improvements:

image

links on the bottom will be displayed in every `--help` window

**To verify**
- `yarn build:packages`
- `npm i -g ./dist/cli`
- `si --help`
- `si hub --help`
- `si seq --help`
- `si inst --help`
- etc.

### CODE REVIEW

**Comment by alicja-gruzdz** [comment]
> * si topic delete

maybe we could use the opportunity and remove this unused code, because the Topics functionality changed and now they can't be removed - ? cc @MichalCz or will something change in this respect in the near future?

**Comment by alicja-gruzdz** [comment]
> * si topic create

I'm also not sure if we need it anymore since the topic is created automatically with the first request?
cc @agne6ka @MichalCz

**Comment by alicja-gruzdz** [comment]
Lookin good :raised_hands: 

Verify for the revealed commands: 
Screenshot from 2022-05-12 11-44-49

**Comment by alicja-gruzdz** [comment]
Verify for the hidden commands:
Screenshot from 2022-05-12 11-49-19

**Comment by alicja-gruzdz** [comment]
Verify for revealing the hidden commands:
Screenshot from 2022-05-12 11-52-19
Screenshot from 2022-05-12 11-53-26

**Comment by alicja-gruzdz** [comment]
One small strange behavior confirmed with @a-tylenda but NOT related to this PR is the hanging response stream when `format` is set to `json` (please see the screen shot below). I don't think it's worth examining at the moment since it concerns the commands which are anyway not implemented:
Screenshot from 2022-05-12 11-59-08

**Review by alicja-gruzdz — APPROVED** [review]

**Comment by alicja-gruzdz** [comment]
The `chalk` is cool. It brings the CLI to life. 
Props for the idea and implementation.

**Review by agne6ka — APPROVED** [review]
Love it 🎨
Awww yea, commander up 💪

**Pull request merged**
