### PR TITLE
Remove instance when failed to start

### PR DESCRIPTION
**Pull request by patuwwy**
**What?**  
Immediately remove Instance when it failed to start by configuration issue.

**Why?**  
https://github.com/scramjetorg/scramjet/issues/124

**Review checks:**

These aspects need to be checked by the reviewer:

- [x] Verify and confirm operation (please post a screenshot) 
- [x] All STH tests pass
- [x] All [Scramjet Cloud Platform](https://docs.scramjet.org/platform) tests pass
- [x] Documentation is updated or no changes

### CODE REVIEW

**Comment by patuwwy** [comment]
Please verify
https://github.com/scramjetorg/scramjet/issues/124
https://github.com/scramjetorg/transform-hub/issues/478

**Comment by BKscramjet** [comment]
Task linked: [SHN-582 [STH] Sequence list vs. Instance list](https://app.clickup.com/t/24308805/SHN-582)

**Review by alicja-gruzdz — APPROVED** [review]
Looks good

**Comment by a-tylenda** [comment]
### verified: 
image


I also checked the same "bad" Sequence with STH without @patuwwy changes, and the Instance appeared on the inst list with the status: `errored`:

image

👏🏼

**Review by a-tylenda — APPROVED** [review]

**Pull request merged**
