### PR TITLE
Python api-client implementation

### PR DESCRIPTION
**Pull request by Tatarinho**
**yarn install:python-deps**

Basic implemantation of api-client with Python.
Client api implemented with aiohttp.

- [x] Separate client to hostclient, instanceclient etc.
- [x] Create BDD tests and run them in CI
- [x] Add setup.py for release
- [x] Add Readme

**Update**
Example BDD tests added:

1. Install dev requirements in your Python environment
`pip3 install -r requirements-dev.txt`

2. Run tests:
```
yarn test:bdd-ci-py
```
3. You can install api-client-py with pip command:
```
pip install git+https://github.com/scramjetorg/transform-hub.git@python-client#subdirectory=packages/api-client-py
```

4. After merge pip command should be without branch name:

```
pip install git+https://github.com/scramjetorg/transform-hub.git#subdirectory=packages/api-client-py
```

5. And then, you can import it:
```
from client.host_client import HostClient
```

### CODE REVIEW

**Review by MichalCz — APPROVED** [review]

**Review by MichalCz — APPROVED** [review]

**Review by alicja-gruzdz — APPROVED** [review]
Excellent work with the api-client and the clear BDD tests.
I verified the tests and I'm attaching the results:
[BDD_Py_LOG.txt](https://github.com/scramjetorg/transform-hub/files/8463044/BDD_Py_LOG.txt)

The only little hiccup I had was that behave didn't install when
`pip3 install -r requirements-dev.txt`
I'll double check with the freeze what could have happened. 
These are the screen shots of the install and run commands I executed:
Zrzut ekranu z 2022-04-11 11-52-20

**Comment by alicja-gruzdz** [comment]
> Client api implemented with aiohttp. To discuss.

Sounds good. From what I'm reading it's designed to work with asyncio, which is probably the most important for us.
It looks like it's fast too: https://www.scrapingbee.com/blog/best-python-http-clients/
What are your experiences with it, would you at this stage consider alternatives?

**Comment by MichalCz** [comment]
@alicja-gruzdz @Tatarinho I'd merge this - it's a functional client for STH, we can work later on middleware and up, but this will already be useful.

**Comment by MichalCz** [comment]
We'd just need a `package.json`.

**Review by MichalCz — APPROVED** [review]

**Pull request merged**
