### PR TITLE
Add yaml loader

### PR DESCRIPTION
**Pull request by MichalCz**
**What?**  

Add yaml loader for config files:

* startup config for IaC mode
* STH config

Potentially also for CLI, but let's not be greedy.

**Why?**  

#571

**How to verify?**

 - [x] Check if you can use the --config argument
 - [x] Check if the config option shows up in the help

### CODE REVIEW

**Comment by daro1337** [comment]
@MichalCz 

I've tested IaC mode. I've found some issues:

1. There is something that sth can't read/load/use `--config` if `--no-docker` argument is not passed at startup
2. `logLevel` is not working if defined in config (always set to trace)
3. `runtimeAdapter` the parameter is not taken into account (probably because I have to test with `--no-docker` argument

Test enviorment:
- minikube STH as kubernetes pod
- STH repo mounted to STH POD
- `yarn start:dev --no-docker -c config.yaml`

config.yaml:
```yaml
runtimeAdapter: kubernetes
logLevel: debug
host:
  port: 9999
  id: 'polololo'
cpmUrl: 'mm-api.default.svc.cluster.local:11000'
cpmId: default
kubernetes:
  namespace: default
  sthPodHost: sth-runner
  runnerImages:
    node: 'scramjetorg/runner:0.99.9'
    python3: 'scramjetorg/runner-py:0.99.9'
  timeout: 0
  runnerResourcesRequestsCpu: 0.01
  runnerResourcesRequestsMemory: 8M
  runnerResourcesLimitsCpu: 0.565
  runnerResourcesLimitsMemory: 1024MB
```
STH runtime config:
```json
{
  "logLevel": "trace",
  "logColors": true,
  "cpmUrl": "mm-api.default.svc.cluster.local:11000",
  "cpmId": "default",
  "docker": {
    "prerunner": {
      "image": "scramjetorg/pre-runner:0.25.0",
      "maxMem": 128
    },
    "runner": {
      "image": "",
      "maxMem": 512,
      "exposePortsRange": [
        30000,
        32767
      ],
      "hostIp": "0.0.0.0"
    },
    "runnerImages": {
      "python3": "scramjetorg/runner-py:0.25.0",
      "node": "scramjetorg/runner:0.25.0"
    }
  },
  "identifyExisting": false,
  "host": {
    "hostname": "0.0.0.0",
    "port": 9999,
    "apiBase": "/api/v1",
    "instancesServerPort": 8001,
    "infoFilePath": "/tmp/sth-id.json",
    "id": "polololo"
  },
  "instanceRequirements": {
    "freeMem": 256,
    "cpuLoad": 10,
    "freeSpace": 128
  },
  "safeOperationLimit": 512,
  "instanceAdapterExitDelay": 9000,
  "runtimeAdapter": "process",
  "startupConfig": "",
  "exitWithLastInstance": false,
  "instanceLifetimeExtensionDelay": 180000,
  "heartBeatInterval": 10000,
  "kubernetes": {
    "namespace": "default",
    "sthPodHost": "sth-runner",
    "runnerImages": {
      "python3": "scramjetorg/runner-py:0.99.9",
      "node": "scramjetorg/runner:0.99.9"
    },
    "timeout": "0",
    "runnerResourcesRequestsCpu": 0.01,
    "runnerResourcesRequestsMemory": "8M",
    "runnerResourcesLimitsCpu": 0.565,
    "runnerResourcesLimitsMemory": "1024MB"
  }
}
```


Also we should add some kind of table with argument / env / config mappig / description

| Config name              | ENV variable               | CMD Parameter                | Required                    | Description                                                     | Example                             |
|--------------------------|----------------------------|------------------------------|-----------------------------|-----------------------------------------------------------------|-------------------------------------|
| id                  | STH_ID                   | --id                   | no                         | STH custom ID

**Review by daro1337 — CHANGES_REQUESTED** [review]
I've tested on kubernetes, requires some changes

**Comment by MichalCz** [comment]
@daro1337 fixed the adapter choice.

**Comment by daro1337** [comment]
> @daro1337 fixed the adapter choice.
`runtimeAdapter` is working, but `logLevel` still does not work

**Review by daro1337 — APPROVED** [review]

**Pull request merged**
