### PR TITLE
Fix: Make STH fetch images ahead of starting host.

### PR DESCRIPTION
**Pull request by a-tylenda**
task: https://app.asana.com/0/1200747048063058/1200787625956055

Activate two BDD scenarios, which include test HUB parameters for setting runner and pre-runner docker images.

### CODE REVIEW

**Review by alicja-gruzdz — APPROVED** [review]

**Comment by MichalCz** [comment]
I made a refactor of `LifeCycleAdapters` to make them available to load on host initialization so that we can replace them in hub on demand (as a first step to what @pietrzakacper suggested on making runner dev not such a hassle - and to be frank much more).

This essentially solves #32 also, and #39 if the right images are given.

To be clear: the host will not expose a port nor will it connect to manager before fetching runner and prerunner images.

**Comment by MichalCz** [comment]
So I got to now have a rather peculiar error, [STH now says here](https://github.com/scramjetorg/transform-hub/runs/3389544197?check_suite_focus=true#step:11:236) that 

```
2021-08-21T14:36:57.385Z log (object:SocketServer) Supervisor connected! ID:  56d495a9-2e48-49b5-b977-000d9a937c4c <and some at signs here>
```

Dunno where do those `@` signs come from, but there's some kind of garbage. Any ideas?

**Comment by patuwwy** [comment]
> Dunno where do those `@` signs come from, but there's some kind of garbage. Any ideas?

guessing... 
supervisor sends it's id as first data then muxed channels are added
host reads id and some bpmux's control data

**Comment by MichalCz** [comment]
> guessing...
> supervisor sends it's id as first data then muxed channels are added
> host reads id and some bpmux's control data

Yup. Looks very much so, which is fairly bad then @patuwwy...

Is this problem also in main?

**Comment by MichalCz** [comment]
Solved in another PR.

**Pull request closed without merging**
