### PR TITLE
Log pretty error when pods quotas are reached

### PR DESCRIPTION
**Pull request by pietrzakacper**
This PR aims to handle most of the situations when Runner Pod fails and we want to know why, in particular:
* reaching max number of Pod's in a namespace (when spawning a new Runner)
* reaching memory limits for a Pod (when Runner Pod is running)

### 1. Reaching max number of Pod's in a namespace
You can set Pods limit applying this command:
```bash
kubectl apply -f <(cat << EOF
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pods-limit
spec:
  hard:
    pods: "1"
EOF
)
``` 

Now when you start STH in a Pod on your cluster:
```bash
 DEVELOPMENT=1 yarn start:dev --runtime-adapter=kubernetes --k8s-namespace=default --k8s-sth-pod-host=sth-runner --k8s-runner-resources-requests-cpu=64m --k8s-runner-resources-requests-memory=100M --k8s-runner-resources-limits-cpu=1000m --k8s-runner-resources-limits-memory=1G
```
and try to start any sequence you should get a following log:
 
image

### 2.  Reaching memory limits for Runner Pod
You can add some memory allocation code like this one, allocating 100MB to you sequence function body:
```ts
Buffer.alloc(1024 * 1024 * 100).fill(0xdeadbeef);
```

Now when you start STH in a Pod on your cluster (Note the memory limits):
```bash
DEVELOPMENT=1 yarn start:dev --runtime-adapter=kubernetes --k8s-namespace=default --k8s-sth-pod-host=sth-runner --k8s-runner-resources-requests-cpu=64m --k8s-runner-resources-requests-memory=50M --k8s-runner-resources-limits-cpu=1000m --k8s-runner-resources-limits-memory=100M 
```
and try to start this memory consuming sequence you should get a following log:

image

### CODE REVIEW

**Comment by a-tylenda** [comment]
I got a different error, is there something missing in the verification process?

image

**Comment by pietrzakacper** [comment]
@a-tylenda Oh yeah I forgot to put that in the verify instruction that in order to run STH in a Pod you have to setup a kubernetes cluster and actually run the STH: https://github.com/scramjetorg/docs/tree/main/developers-instructions/transform-hub-k8s on a cluster. The more detailed instructions would be:

1. Install and start minikube and kubectl 
Open terminal anywhere:
```bash
curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
sudo install minikube-linux-amd64 /usr/local/bin/minikube
curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
kubectl version --client
minikube start --extra-config=apiserver.service-node-port-range=8000-65535
```

2. Create a Pod with STH
Open terminal in `developers-instructions/transform-hub-k8s` of the [docs repo](https://github.com/scramjetorg/docs/tree/main/developers-instructions/transform-hub-k8s), possibly you also need to edit the STH image name as it's hardcoded: https://github.com/scramjetorg/docs/blob/main/developers-instructions/transform-hub-k8s/deploy-sth-dev.sh#L27
Change it for any STH image you have locally e.g. `scramjetorg/sth:0.21.0`  and then run the script:
```bash
./deploy-sth-dev.sh <k8s-namespace> <sth_path>
# e.g ./deploy-sth-dev.sh default ~/Projects/scramjet-cpm-dev/sth
```
This will create a Pod for STH but there won't be actual STH running in it yet.

3. Copy source code of STH and run it
Open terminal in STH:
```bash
kubectl exec -i sth -- mkdir -p /sth
tar cf - --exclude='node_modules/*' . | kubectl exec -i sth -- tar xvf - -C /sth
kubectl exec -it sth -- bash
> cd /sth
>  DEVELOPMENT=1 yarn start:dev --runtime-adapter=kubernetes --k8s-namespace=default --k8s-sth-pod-host=sth-runner --k8s-runner-resources-requests-cpu=64m --k8s-runner-resources-requests-memory=100M --k8s-runner-resources-limits-cpu=1000m --k8s-runner-resources-limits-memory=1G
```

4. Now you can interact with STH through `minikube ip`
In order to use it in CLI you have to set the apiUrl:
```bash
si config set apiUrl http://$(minikube ip):8000/api/v1
```

5. Now you should be able to send a sequence through CLI

**Comment by daro1337** [comment]
Thanks @pietrzakacper , it works great. :)

```bash
[sth-0] 2022-05-19T09:12:56.446Z ERROR KubernetesClientAdapter Running "Create Pod" responded with error [ 
[sth-0]   'pods "runner-764b155f-f765-45b4-bd56-c1545ef3ca1a" is forbidden: exceeded quota: pods-limit, requested: pods=1, used: pods=7, limited: pods=7' 
--
[sth-0] 2022-05-19T09:12:57.457Z ERROR KubernetesClientAdapter Running "Create Pod" responded with error [ 
[sth-0]   'pods "runner-764b155f-f765-45b4-bd56-c1545ef3ca1a" is forbidden: exceeded quota: pods-limit, requested: pods=1, used: pods=7, limited: pods=7' 
--
[sth-0] 2022-05-19T09:12:59.464Z ERROR KubernetesClientAdapter Running "Create Pod" responded with error [ 
[sth-0]   'pods "runner-764b155f-f765-45b4-bd56-c1545ef3ca1a" is forbidden: exceeded quota: pods-limit, requested: pods=1, used: pods=7, limited: pods=7' 

```

**Review by daro1337 — APPROVED** [review]

**Review by a-tylenda — APPROVED** [review]

**Comment by daro1337** [comment]
> @daro1337 thanks for verifying this. Did you perhaps also notice what was an error and message returned from the API?

I'm not sure which API you mean. This error is from the kube-apiserver.

Generally STH asks the kube-apiserver to create a POD with a runner but the limit is reached so the runner POD is not created, then  STH returns this error, so the sequence is on STH but could not be copied to the runner.

**Pull request merged**
